### ISSUE TITLE
Palettes by size -- feature request?

### ISSUE THREAD

**Issue by vreuter** [caleblareau/BuenColors#1]
Where possible, I try to choose a palette for which the number of colors is exactly the number that I want to use. Is there a function that takes a number as an argument and returns each of the palettes with that many colors?
If so, I'd definitely use it, though I'm not sure how popular it'd be in general. If that doesn't exist and there isn't interest in including it, is there a function or straightforward way to list all the palette names? Then I could do something like `Filter(function(p) length(jdb_palette(p)) == n, all_palette_names)`
Thanks in advance!

**Comment by caleblareau** [comment]
Not the most elegant solution but, note that `jdb_palettes` is a named list that exists in the namespace when you load the package. So, you can easily get the lengths of each palette like so: 

```
sapply(jdb_palettes, length)
```
And then, yannow, if you want say palettes with 5 colors...
```
jdb_palettes[sapply(jdb_palettes, length) == 5]
```
@vreuter does this work?

**Comment by vreuter** [comment]
Ah! Yep, that's perfect; the `jdb_palettes` is the hook that I didn't realize was there. I'd just been using `jdb_palette` as a function to fetch by name. Thank you!
