### ISSUE TITLE
palette of corona is missing

### ISSUE THREAD

**Issue by pangxueyu233** [caleblareau/BuenColors#3]
Hi,

it's really a interesting tool to help us set the color of graph. Recently, we want use this package to optimize the visualization of our single cell map. When I tried to use ```jdb_palette("corona")```, it reported an error that ```"Error in jdb_palette("corona") : Palette not found."```.
And I checked ```names(jdb_palettes)```, there isn't a palette named ```corona```.
Can you tell me how could we call  ```corona``` palette in your package ?

Thanks a lot!

**Comment by caleblareau** [comment]
Hmm.. it was a fairly recent addition, but it should be there... Can you confirm that you are using `v0.5.6` of the package ?

**Comment by pangxueyu233** [comment]
Oh, I see, my package is ```v0.5.5```, I will update this package to ```v0.5.6```. Thanks for your immediately replying.
