### ISSUE TITLE
Create Release(s)

### ISSUE THREAD

**Issue by mfansler** [caleblareau/BuenColors#5]
It would be helpful for reproducibility to have proper GitHub Release(s).

**Comment by caleblareau** [comment]
Just created a release-- does this help with the workflow?

**Comment by mfansler** [comment]
Thanks! ❤️  

This helps automate downstream tracking in Bioconda - i.e., new Releases will be auto-detected and distributed. It covers my purposes (closing), but not sure about `rworkflows` (maybe that's what you meant by "workflow"?).
